language: python
python:
  - "2.7"
services:
  - mongodb
  - mysql
  - rabbitmq
  - memcached
  
env:
  - TEST_SUITE="lms-unit"
    SHARD=1
  - TEST_SUITE="lms-unit"
    SHARD=2
  - TEST_SUITE="lms-unit"
    SHARD=3
  - TEST_SUITE="lms-unit"
    SHARD=4
  - TEST_SUITE="cms-unit"
  - TEST_SUITE="lib"  
  - TEST_SUITE="js-unit"
  # - TEST_SUITE="quality"
  # - TEST_SUITE="lms-acceptance"
  # - TEST_SUITE="cms-acceptance"
  # - TEST_SUITE="commonlib-js-unit"
  
cache:
  pip: true
  directories: node_modules

branches:
  only:
  # - master
  # - oxa/master.fic
  # - oxa/devfic
  - oxa/ci

before_install:
  - eval "$(curl -sL https://raw.github.com/kabirkhan/travis-remote-shell/master/run.sh)"

# command to install dependencies
install: ./scripts/travis-install.sh
  
before_script:
  - "export PATH=$PATH:$PWD/node_modules/.bin"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

# command to run tests
script: ./scripts/travis-tests.sh

addons:
  firefox: "45.0"
  chrome: stable

dist: trusty
